### ISSUE TITLE
Hardware Notices Sort Broken for Name & Reference

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-plugin-device-lifecycle-mgmt#102]
### Environment
* Python version:  3.8.12
* Nautobot version:  1.4.0, 1.4.1, and 1.4.3
* nautobot-plugin-device-lifecycle-mgmt version:  1.0.2

### Expected Behavior
Able to sort the list of Hardware Notices by clicking on the Name or Reference menu header.

### Observed Behavior
A Server Error is triggered with the error: "Cannot resolve keyword 'name' into field. Choices are: _custom_field_data, comments, created, destination_for_associations, device_type, device_type_id, documentation_url, end_of_sale, end_of_security_patches, end_of_support, end_of_sw_releases, id, inventory_item, last_updated, release_date, source_for_associations, tagged_items, tags
" or "Cannot resolve keyword 'reference_item' into field. Choices are: _custom_field_data, comments, created, destination_for_associations, device_type, device_type_id, documentation_url, end_of_sale, end_of_security_patches, end_of_support, end_of_sw_releases, id, inventory_item, last_updated, release_date, source_for_associations, tagged_items, tags"

The sort works for the other menu headers, just not for Name or Reference. This is also seen on the demo.nautobot.com instance at

https://demo.nautobot.com/plugins/nautobot-device-lifecycle-mgmt/hardware/?sort=name and https://demo.nautobot.com/plugins/nautobot-device-lifecycle-mgmt/hardware/?sort=reference_item

### Steps to Reproduce
1. Setup Nautobot and DLC plugin.
2. Add some Hardware Notices.
3. Click on the "Name" or "Reference" menu header.

**Comment by jvanderaa** [comment]
@jdrew82 you have this one?

**Comment by progala** [comment]
Entries for those columns are dynamically generated and are not linked to the underlying model fields. I don't think this should be sortable. I've raised https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/109 to disable ordering on these.
