### ISSUE TITLE
Version 1.1.0 is minor bump, but breaks build from 1.0.x versions due to updated config requirements

### ISSUE THREAD

**Issue by jmcgill298** [nautobot/nautobot-plugin-device-lifecycle-mgmt#118]
### Environment
* Python version:   3.8
* Nautobot version:   1.2.7
* nautobot-plugin-device-lifecycle-mgmt version:   1.1.0

### Expected Behavior
Existing Nautobot Plugins Config to work from DLM v1.0.2

### Observed Behavior
Version 1.1.0 of DLM requires a new variable to be defined in the config, and Nautobot fails to launch

### Steps to Reproduce
1.
2.
3.

**Comment by bradh11** [comment]
This appears to be a bug introduced in the most recent update as part of [PR83](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/issues/83) .  The proposed solution is to remove the new variable `barchart_bar_width` as a requirement in the nautobot_config file and instead honor a default setting for it.

**Comment by bradh11** [comment]
This will be addressed as part of PR https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/119.
