### ISSUE TITLE
Tests Fail on 1.5.4

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-device-lifecycle-mgmt#124]
### Environment
* Python version:   3.9.x
* Nautobot version:   1.5.4
* nautobot-plugin-device-lifecycle-mgmt version:   Latest

### Expected Behavior

Tests to pass

### Observed Behavior

Tests are failing on 1.5.4, but not 1.5.1

### Steps to Reproduce
1. Change `"nautobot_ver": "1.5.4",` from 1.5.1
2. See the failure
3.

Seen during #123

**Comment by bradh11** [comment]
Addressed in https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/125

**Comment by bryanculver** [comment]
🤦 https://github.com/nautobot/nautobot/issues/2948
