### ISSUE TITLE
Add capability to get Validated Softwares per given device

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot-plugin-device-lifecycle-mgmt#14]
### Proposed Functionality

Add capability to fetch Validated Softwares per given device. This could be potentially a `device filter`. This should be covered by both GraphQL and REST APIs.

Example query (pseudocode):
```
query {
  validated softwares(device: "warsaw-rtr-01") {
    name
  }
}
```

### Use Case

As a Network Automation Engineer, I want to fetch a list Validated Softwares for a given device. List of Validated Softwares is useful to me, to perform checks if particular software has been approved for a given device.

**Comment by progala** [comment]
This functionality was added in PR https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/16 and merged into the main.
