### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-plugin-device-lifecycle-mgmt#143]
### Environment
* Nautobot version:  1.5.13 (to get `metrics.py` support)
* nautobot-plugin-device-lifecycle-mgmt version:  latest

### Proposed Functionality

Expose Prometheus metrics for this app. Examples:

#### Device Software Validation Report

This GUI view shows a graph that details how many devices have valid platforms. Metrics that _could_ be generated from this:

- `nautobot_device_lifecycle_compliant_by_platform_total{platform="Arista EOS", status="compliant"} 160.0`
- `nautobot_device_lifecycle_compliant_by_device_type_total{device_type="Catalyst 6509-E", status="compliant"} 35.0`

Further metrics could be useful, these are just examples I was able to think of.

### Use Case

Allow users of the platform to generate time series from their Nautobot instance. In the end this could for example lead to creation of NOC dashboards or alerting based on this data.

**Comment by zackt25** [comment]
I don't have write access so had to make my own branch
