### ISSUE TITLE
Add a hashing algorithm field to SoftwareImageLCM model

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot-plugin-device-lifecycle-mgmt#144]
### Environment
* Nautobot version:  1.5.10
* nautobot-plugin-device-lifecycle-mgmt version: 1.1.2

### Proposed Functionality
Add a field to the SoftwareImageLCM model to signify the hashing algorithm that the checksum is derived from.

### Use Case
As P.D. the Plugin Developer I would like to write a script to download a software image using the `download_url` and verify the hash of the file via `image_file_checksum` afterward. Since the `image_file_checksum` field is simply a CharField, there is no definitive way to know which hashing algorithm was used to create it (MD5, SHA1, SHA256, SHA512, etc). A current workaround would be to assume the algorithm based on the string length.

**Comment by progala** [comment]
That's a good idea. Would we want to pre-define the available options or have it define as a char field?

**Comment by joewesch** [comment]
We can do it as a CharField on the model and then have the choices only on the form. This would allow for adding options to the choices without a migration file in the future.
