### ISSUE TITLE
Missing Software -- Virtual Machine Relationship

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-device-lifecycle-mgmt#172]
### Environment
* Python version:  3.9
* Nautobot version:  1.5.18
* nautobot-plugin-device-lifecycle-mgmt version: 1.2

### Expected Behavior

Expected to be able to relate software image/LCM to Virtual Machine. This may relate to: 

- UCS Manager software
- Virtualized systems on a NFV

### Observed Behavior

No relationship to virtual machine

### Steps to Reproduce
1. 
2.
3.

**Comment by smk4664** [comment]
This is a duplicate, see issue #115
