### ISSUE TITLE
Software to CVE should be concrete ManytoMany field instead of Relationship

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-plugin-device-lifecycle-mgmt#179]
### Environment
* Nautobot version:  1.5.4
* nautobot-plugin-device-lifecycle-mgmt version:  1.2.0

### Proposed Functionality

Move Software to CVE relationship into a ManyToMany field.

### Use Case

Currently Software to CVE is done through Relationships. This is neat, but adds to lengthy delays as you cannot do select_related with Generic Foreign keys.  In addition, we could put a list of all the CVE's or all the Software connected to a CVE on the detail page, instead of a link to the list.

**Comment by glennmatthews** [comment]
Seems like this would be desirable for SoftwareLCM-to-Device as well?

**Comment by bradh11** [comment]
targeting this for 2.X release

**Comment by progala** [comment]
Resolved by #213
