### ISSUE TITLE
Contract currency filter not working

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot-plugin-device-lifecycle-mgmt#187]
### Environment
* Python version:  3.7.16
* Nautobot version:  1.5.7
* nautobot-plugin-device-lifecycle-mgmt version:  1.1.2

### Expected Behavior
To be able to filter Contract by currency

### Observed Behavior
> Invalid filters were specified:
   &nbsp;- currency
   &nbsp;&nbsp;- Unknown filter field

### Steps to Reproduce
1. Go to Contract List View (i.e. on [demo site](https://demo.nautobot.com/plugins/nautobot-device-lifecycle-mgmt/contract/))
2. Click Filter button
3. Choose any currency (or just let it default to the first one)
4. Click Apply

**Comment by qduk** [comment]
This looks to also affect filtering as a whole. Since I can't deselect a currency, when I try to filter using any of the other fields it fails with the aforementioned error.
