### ISSUE TITLE
Where Is the Export Button For Devices Under a Contract

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-device-lifecycle-mgmt#191]
### Environment
* Python version:  
* Nautobot version:  
* nautobot-plugin-device-lifecycle-mgmt version:  

### Expected Behavior

Expected to be able to get an export of devices that are part of a contract.

### Observed Behavior

No export button

### Steps to Reproduce
1. Go to DLM Plugin Menu
2. Select the devices for a contract
3. Navigate to the related devices
4. Expect to be able to export this list

**Comment by progala** [comment]
Thanks @jvanderaa . Are you referring to the relationship associations list, e.g. https://demo.nautobot.com/extras/relationship-associations/?relationship=contractlcm-to-device&source_id=6e281cbb-442c-44e0-b6e9-309538b1f86f ?

**Comment by jvanderaa** [comment]
Exactly there. Some how we need to provide a report that can be done of devices under a contract. Something that can be exported to be used in something like a smart net validation.

**Comment by bradh11** [comment]
@jvanderaa  We took a look at this and determined this is not coming from the Device Lifecycle application.  This page is part of Nautobot Core.  There is work being done to redefine the table export capabilities in Nautobot 2.0. I would recommend taking this issue up with Nautobot Core project. 

Thanks!

**Comment by bradh11** [comment]
closing due to this being outside of the device lifecycle codebase.
