### ISSUE TITLE
Enhance ValidatedSoftware associations

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot-plugin-device-lifecycle-mgmt#21]
### Existing Functionality
The plugin allows for limited flexibility when working with ValidatedSoftware model instances.

The user is limited to create **only one of the following** per the single ValidatedSoftware instance:
- one association to Device
- one association to DeviceType
- one association to InventoryItem

### Proposed Functionality
While working with networks of hundreds or thousands of objects, it has been identified current way of managing the ValidatedSoftware is cumbersome.

Most likely, a given software release will be applicable to multiple Device(s) or multiple DeviceType(s) or multiple InventoryType(s) or Groups having the same lifecycle (valid from, valid until etc.).

Proposed functionality assumes following:
ValidatedSoftware instance pointing to a mix of Device, DeviceTypes and CustomGroups (https://github.com/nautobot/nautobot/issues/896).

### Use Case

As a Network Engineer, I want to have limited number of ValidatedSoftware to ease maintenance.

As a Network Engineer, I want to assign a ValidatedSoftware instance (one) for different and multiple types of objects (mix of Device, DeviceTypes and objects groups.)

**Comment by progala** [comment]
Raised https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/32 which implements multiple object assignments for `ValidatedSoftware`.

**Comment by dgarros** [comment]
Fixed in #32
