### ISSUE TITLE
Typo in migration causing upgrades to 2.x to fail

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot-plugin-device-lifecycle-mgmt#249]
https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/blob/825190a30eea56b55d1d22f4f03a138248ccb10e/nautobot_device_lifecycle_mgmt/migrations/0016_role_migration_cleanup.py#L33

That line incorrectly references `nautobot_device_onboarding` instead of `nautobot_device_lifecycle_mgmt`

**Comment by progala** [comment]
Fixed in 2.0.2
