### ISSUE TITLE
Allow "Object Assigned To" to reference multiple objects

### ISSUE THREAD

**Issue by brobare** [nautobot/nautobot-plugin-device-lifecycle-mgmt#31]
### Environment
* Nautobot version:  1.1.4
* nautobot-plugin-device-lifecycle-mgmt version:  0.2.1

### Proposed Functionality
Currently, when creating a ValidatedSoftware object, it only allows for reference to a single Device/DeviceType/InventoryItem. Would be good to have this able to reference multiple.

### Use Case
As Nelly the Network Engineer, I define all of the validated software for Initec, Inc. Our company uses many different models of the Juniper SRX3xx family of devices. The SR3xx devices use the same code base, across many models. For example, we will specify `18.4R2-S6.3` for SRX300, SRX320, SRX340, etc. We would like to be able to create a single ValidatedSoftware entry that can reference all of these models.

**Comment by dgarros** [comment]
@brobare, we realized the same recently and we are already working on an enhancement to associate ValidatedSoftware with a group of devices. @progala is actively working on it
@progala please can you provide an overview of that you are working on when you get a chance. thanks

**Comment by progala** [comment]
@brobare @dgarros 

I raised https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/32 which implements multiple object assignments for `ValidatedSoftware`.

With this enhancement one validated software object can be assigned to multiple other objects. These include devices, device types, device roles, inventory items and tags applied to any of the preceding.

**Comment by progala** [comment]
This has been now implemented and is available from [v0.3.0](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/releases/tag/v0.3.0)
