### ISSUE TITLE
Availability of this plugin in demo.nautobot.com

### ISSUE THREAD

**Issue by vladanmilosevic73** [nautobot/nautobot-plugin-device-lifecycle-mgmt#34]
Hi,
I have noticed that the demo.nautobot.com does not have this plugin installed. Is it possible to add it there?

### **Environment**
demo Nautobot page

### **Expected Outcome**
Device Lifecycle Management Plugin available in demo.nautobot.com

**Comment by progala** [comment]
Hi @vladanmilosevic73,

It would indeed be great to have this plugin in the demo.nautobot.com. I will look into having it added there.

**Comment by dgarros** [comment]
This plugin is now available on https://demo.nautobot.com/ thanks to @progala
