### ISSUE TITLE
Enhance reporting functionality

### ISSUE THREAD

**Issue by progala** [nautobot/nautobot-plugin-device-lifecycle-mgmt#38]
### Proposed Functionality

There is often need to have an overview of which Devices/Inventory Items are running valid software or have maintenance contracts in place. Furthermore, there should be a filtering functionality provided so that the reports can be generated on the fly for the subset of the Devices/Inventory Items selected across different dimensions.

These reports should be provided in graphical and tabular forms with the ability to download the images and export data in CSV, or similar, format.

### User Story

As Nelly the Network Engineer,
I want to be able to see a summary of the software versions that are valid/invalid. I want to be able to filter the summary using attributes of Devices/Inventory Items and export the results in graphical and CSV forms.

I know this is done when:

- I can go to a page called "Validated Software Reports" and can see overview with breakdown by device platforms/models etc.
- I can apply filters by choosing device roles/devices/software version to generate reports of interest.
- I can save charts by right clicking on the images and generate CSV exports by clicking on export button on the report page.

**Comment by dgarros** [comment]
I imagine we'll need reports for all features : software, hardware and maintenance contracts.
Is it realistic to add support for all at once or should we break that down into 3 issues and implement them separately ? 

If we decide to implement the reports separately it would be great to ensure that the design will apply to all 3 features.
