### ISSUE TITLE
Error when having more than 57 softwares in the list

### ISSUE THREAD

**Issue by joakimnyden** [nautobot/nautobot-plugin-device-lifecycle-mgmt#44]
### Environment
* Python version:  3.6.8
* Nautobot version:  1.1.5
* nautobot-plugin-device-lifecycle-mgmt version:  0.2.2

### Expected Behavior
When adding more then 57 softwares we get template error.

### Observed Behavior
**from debug output:**
UnboundLocalError at /plugins/nautobot-device-lifecycle-mgmt/software/
local variable 'template' referenced before assignment
Request Method: GET
Request URL: https://...../plugins/nautobot-device-lifecycle-mgmt/software/
Django Version: 3.1.13
Exception Type: UnboundLocalError
Exception Value: local variable 'template' referenced before assignment
Exception Location: /opt/nautobot/lib64/python3.6/site-packages/nautobot/utilities/tables.py, line 371, in render
Python Executable: /usr/bin/python3.6
Python Version: 3.6.8
Python Path: ['.',
'',
'/opt/nautobot',
'/opt/nautobot/lib64/python3.6/site-packages/git/ext/gitdb',
'/opt/nautobot/bin',
'/usr/lib64/python36.zip',
'/usr/lib64/python3.6',
'/usr/lib64/python3.6/lib-dynload',
'/opt/nautobot/lib64/python3.6/site-packages',
'/opt/nautobot/lib/python3.6/site-packages',
'/opt/nautobot/lib64/python3.6/site-packages/gitdb/ext/smmap',
'/opt/nautobot/git/jobs/jobs']
Server time: Tue, 14 Dec 2021 09:54:54 +0100

### Steps to Reproduce
1. Have 57 softwares in the list
2. Create one more software

### Steps to recover
1. remove the latest software created

**Comment by progala** [comment]
Thanks for opening an issue @joakimnyden . 

Is the error occurring when you try navigating to the Software List view?

Is there any chance you could share the data you're using for your Software objects? I have ca. 200 objects in one of my environments and have not experienced any issues.

Also, have you tried adding a new Software objects with different attributes?

**Comment by joakimnyden** [comment]
Hi, 
I have included the data from the software list view. we have tried diffrent attributes but no difference.
The last coloumn "vulnerability" is a CF Field that we tag if we find any vulnerability.

Hope you can trigger the same issue with this data.

[nautobot_Softwares.csv](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/files/7744321/nautobot_Softwares.csv)

**Comment by joakimnyden** [comment]
Fond the issue, it was the cf_field that got sad when we don't assign any value.

Think you can close the issue.

**Comment by progala** [comment]
Thank you for the update. Glad to hear you were able to find the problem.
