### ISSUE TITLE
 Provide API Documentation

### ISSUE THREAD

**Issue by pugnacity** [nautobot/nautobot-plugin-device-lifecycle-mgmt#51]
### Environment
* Nautobot version:  1.2.1
* nautobot-plugin-device-lifecycle-mgmt version:  0.3.0

### Expected Behavior

Documentation which shows how the plugin could be used via the REST API

**Comment by dgarros** [comment]
@pugnacity the documentation for the API is available as part the main API documentation
you should be able to see an example here https://demo.nautobot.com/api/docs/ 

<img width="1860" alt="Screen Shot 2022-01-10 at 10 56 49 AM" src="https://user-images.githubusercontent.com/304126/148796703-907b1560-4b85-48f0-95bf-7b9bc10d77d5.png">
