### ISSUE TITLE
CVE Modeling

### ISSUE THREAD

**Issue by josh5276** [nautobot/nautobot-plugin-device-lifecycle-mgmt#52]
### Environment
* Nautobot version:  1.2.x
* nautobot-plugin-device-lifecycle-mgmt version:  v0.3.0

### Proposed Functionality
Add a method to which CVEs can be tracked and associated to assets within Nautobot.

The first model should be a standard CVE model that can be generalized CVE data with relationships to a software model. (Many to Many)
The second model would be a vulnerability model that would be created for a device/inventory-item <-> CVE basis to create a vulnerability for a given asset. The vulnerability model would need to support custom fields to allow notations and specific customizations depending on how the vulnerability will be handled. 

Something like this, as an example:
<img width="641" alt="Screen Shot 2022-01-12 at 10 45 26 AM" src="https://user-images.githubusercontent.com/7542351/149184047-12f320c4-55a5-4d83-acca-eea54ecbe127.png">

### Use Case
As Sam the Network Security Engineer, I would like to extend the current functionality of the device llfecycle plugin to track CVEs and security vulnerabilities on a per-device, per-software basis. I think this could be accomplished with a basic CVE model within the plugin, along with an additional model to correlate a device/software to a CVE as a "vulnerability"

**Comment by joewesch** [comment]
Completed in #57
