### ISSUE TITLE
GraphQL query for software validation results based on device causes error

### ISSUE THREAD

**Issue by bminnix** [nautobot/nautobot-plugin-device-lifecycle-mgmt#79]
### Environment
* Python version:  3.7.12
* Nautobot version:  1.2.7
* nautobot-plugin-device-lifecycle-mgmt version:  0.4.1

### Expected Behavior
When running GraphQL query
```
query {
  devices {
    name
    id
    device_software_validation {
      id
    }
    rel_device_soft { version }
  }
}
```
Expect to see ID of software validation results

### Observed Behavior
```
"errors": [
    {
      "message": "'DeviceSoftwareValidationResult' object has no attribute 'all'"
```

### Steps to Reproduce
1. See steps above

This seems to be related to Issue: https://github.com/nautobot/nautobot/issues/1313

**Comment by progala** [comment]
Fixed in core Nautobot in: https://github.com/nautobot/nautobot/pull/1600
